### ISSUE TITLE
runtimepath にないプロジェクトにも飛びたい

### ISSUE THREAD

**Issue by thinca** [sgur/vim-gf-autoload#3]
私は普段開発中のプロジェクトは `'runtimepath'` に含めないようにしているのですが、`gf-autoload` は `'runtimepath'` から対象のファイルを探してくるので、開発中のプロジェクト内でジャンプができません。
これができるようになると嬉しいです。
具体的な方法が難しいですが、個人的には、以下のどちらかの方法で達成可能です。
1. `getcwd()` の結果を `'runtimepath'` の先頭に追加した上で検索を行う
   - 私は普段プロジェクトルートに `:lcd` して開発を行っているのでこれで十分なのですが、あまり汎用的な方法ではないです。
2. 開いているファイルのパスを上方向に辿っていき、`autoload` ディレクトリが存在するディレクトリが見つかったら、そのディレクトリを `'runtimepath'` の先頭に追加した上で検索を行う

他にアイディアがあれば他の方法でも問題ありません。
また、内容は許容できるけども実装するのが(時間的/技術的など様々な面で)難しいということであれば PR も考えているので、教えて頂けると嬉しいです。

**Comment by sgur** [comment]
なるほど。確かに需要はありそうですね。
プラグイン等を遅延ロードしている関係で `&rtp` に存在してないケースも有り得そうです。

たとえば、以下の順に検索していくのはどうでしょうか？

1. `b:autoload_gf_basedir` (あれば)
2. `getcwd()`
3. `finddir("autoload", expand("%:p:h") . ";")`
4. `&runtimepath`

**Comment by thinca** [comment]
とても良いと思います！ :+1:

**Comment by sgur** [comment]
修正しました。想定した挙動になっているか、試して頂けますか？

**Comment by thinca** [comment]
Issue の存在を完全に忘れていましたが、バッチリ動いてます！今でも便利に使わせてもらってます！
